apiVersion: v1
kind: ConfigMap
metadata:
  name: orderservice-config
data:
  SERVER_PORT: "8080"
  ORDERSERVICE_DB_URL: "jdbc:postgresql://orderservice-db:5432/orderservice"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus"

