apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orderservice-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice-postgres
  labels:
    app: orderservice-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderservice-postgres
  template:
    metadata:
      labels:
        app: orderservice-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_DB
              value: orderservice
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: orderservice-secret
                  key: ORDERSERVICE_DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orderservice-secret
                  key: ORDERSERVICE_DB_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: orderservice-postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: orderservice-db
  labels:
    app: orderservice-postgres
spec:
  type: ClusterIP
  selector:
    app: orderservice-postgres
  ports:
    - port: 5432
      targetPort: 5432

